-- =============================================================================
-- Migration: 001_init.sql
-- Project:   Migración Bancos - Ofertas Recibidas
-- Date:      2026-05-22
-- Author:    Supabase Data Specialist
--
-- SECURITY NOTE:
--   service_role key MUST NEVER be exposed in browser or frontend code.
--   Apps Script uses service_role via server-side HTTP calls only.
--   The anon key is safe for read-only dashboard access via RLS policies below.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- provides gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";   -- trigram indexes for text search


-- =============================================================================
-- ENUM: normalized_status
-- Canonical set of states for every sheet_row and dispatch_attempt.
-- =============================================================================
CREATE TYPE normalized_status AS ENUM (
    'pending_ready',
    'blocked_red_flag',
    'blocked_missing_docs',
    'blocked_validation',
    'sent',
    'sending',
    'failed',
    'relaunch_requested',
    'offer_received',
    'rejected',
    'more_info_requested',
    'unknown'
);


-- =============================================================================
-- TABLE: banks
-- Master catalogue of the 22 active banks.
-- Populated once; updated manually when a new bank tab is added to the Sheet.
-- =============================================================================
CREATE TABLE IF NOT EXISTS banks (
    id                  SERIAL          PRIMARY KEY,
    slug                TEXT            NOT NULL UNIQUE,       -- 'ibercaja', 'ing', 'deutsche_bank'
    name                TEXT            NOT NULL,              -- display name
    sheet_name          TEXT            NOT NULL,              -- exact Google Sheet tab name
    active              BOOLEAN         NOT NULL DEFAULT TRUE,
    has_uid_column      BOOLEAN         NOT NULL DEFAULT FALSE, -- sheet has ITEM ID / UID column
    has_process_status  BOOLEAN         NOT NULL DEFAULT FALSE, -- sheet has Process Status column
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  banks IS 'Catalogue of banks. One row per active Google Sheet tab.';
COMMENT ON COLUMN banks.slug IS 'URL-safe unique identifier used in code and API routes.';
COMMENT ON COLUMN banks.sheet_name IS 'Exact tab name in the Google Sheet. Used by Apps Script to map rows.';
COMMENT ON COLUMN banks.has_uid_column IS 'True when the bank sheet contains an ITEM ID / UID column generated by Apps Script.';
COMMENT ON COLUMN banks.has_process_status IS 'True when the bank sheet contains a Process Status column.';


-- ---------------------------------------------------------------------------
-- Seed: 22 active banks
-- slug is lowercase with underscores; sheet_name is the real tab label.
-- ---------------------------------------------------------------------------
INSERT INTO banks (slug, name, sheet_name, active, has_uid_column, has_process_status) VALUES
    ('santander',       'Santander',        'Santander',        TRUE, TRUE,  TRUE),
    ('uci',             'UCI',              'UCI',              TRUE, TRUE,  TRUE),
    ('ing',             'ING',              'ING',              TRUE, TRUE,  TRUE),
    ('ruralnostra',     'Ruralnostra',      'Ruralnostra',      TRUE, FALSE, FALSE),
    ('ibercaja',        'Ibercaja',         'Ibercaja',         TRUE, TRUE,  TRUE),
    ('cr_teruel',       'CR Teruel',        'CR Teruel',        TRUE, FALSE, FALSE),
    ('unicaja',         'Unicaja',          'Unicaja',          TRUE, TRUE,  TRUE),
    ('no_bank_fee',     'No Bank Fee',      'No Bank Fee',      TRUE, FALSE, FALSE),
    ('cr_asturias',     'CR Asturias',      'CR Asturias',      TRUE, FALSE, FALSE),
    ('cr_aragon',       'CR Aragón',        'CR Aragón',        TRUE, FALSE, FALSE),
    ('cr_granada',      'CR Granada',       'CR Granada',       TRUE, FALSE, FALSE),
    ('laboral_kutxa',   'Laboral Kutxa',    'Laboral Kutxa',    TRUE, TRUE,  TRUE),
    ('deutsche_bank',   'Deutsche Bank',    'Deutsche Bank',    TRUE, TRUE,  TRUE),
    ('eurocajarural',   'EuroCajaRural',    'EuroCajaRural',    TRUE, FALSE, FALSE),
    ('myinvestor',      'MyInvestor',       'MyInvestor',       TRUE, TRUE,  TRUE),
    ('cr_del_sur',      'CR del Sur',       'CR del Sur',       TRUE, FALSE, FALSE),
    ('globalcaja',      'Globalcaja',       'Globalcaja',       TRUE, FALSE, FALSE),
    ('caixa_popular',   'Caixa Popular',    'Caixa Popular',    TRUE, FALSE, FALSE),
    ('cajamar',         'Cajamar',          'Cajamar',          TRUE, TRUE,  TRUE),
    ('bankinter',       'Bankinter',        'Bankinter',        TRUE, TRUE,  TRUE),
    ('kutxabank',       'Kutxabank',        'Kutxabank',        TRUE, TRUE,  TRUE),
    ('abanca',          'Abanca',           'Abanca',           TRUE, TRUE,  TRUE)
ON CONFLICT (slug) DO NOTHING;


-- =============================================================================
-- TABLE: sheet_rows
-- One row per (bank, opportunity_id) pair — mirrors every row of every Sheet tab.
-- This is the central fact table. Apps Script upserts here on every sync.
--
-- CRITICAL CONSTRAINT: UNIQUE(bank_id, opportunity_id)
--   Prevents duplicate submissions per bank. Any attempt to insert a second row
--   for the same bank+opportunity must be handled as an UPDATE, not an INSERT.
-- =============================================================================
CREATE TABLE IF NOT EXISTS sheet_rows (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Source identifiers
    uid                     TEXT            UNIQUE,             -- ITEM ID from Apps Script (nullable for banks without UID column)
    bank_id                 INT             NOT NULL REFERENCES banks(id) ON DELETE RESTRICT,
    opportunity_id          BIGINT          NOT NULL,           -- Pipedrive Opportunity ID
    bank_deal_id            BIGINT,                             -- ID of deal at the bank's system

    -- Client & loan data
    nombre_cliente          TEXT            NOT NULL,
    importe                 NUMERIC(12, 2),                     -- loan amount in EUR
    link_dossier            TEXT,                               -- Google Drive URL

    -- Timing
    timestamp_entry         TIMESTAMPTZ,                        -- when the row was entered in the Sheet
    send_trigger            BOOLEAN,                            -- normalized from "Enviado/Enviar": Yes→true, No/blank→false/null
    timestamp_sent          TIMESTAMPTZ,                        -- when Apps Script marked it as sent

    -- Status (dual: raw for auditability, normalized for queries)
    status_raw              TEXT,                               -- original value from Sheet, never overwritten
    status                  normalized_status,                  -- computed normalized state

    -- Red flags (dual: raw string and parsed array)
    red_flags_raw           TEXT,                               -- original pipe-separated string from Sheet
    red_flags               TEXT[],                             -- array: each element is one trimmed red flag text

    -- Bank-specific optional columns
    clasificacion           TEXT,
    dossier                 TEXT,
    auto_bayteca            TEXT,                               -- 'NO' or empty
    auto_banco              TEXT,
    autorizacion            TEXT,
    autorizacion_link       TEXT,
    autorizacion_red_flag   TEXT,
    process_status          TEXT,                               -- 'Completado', 'Procesando', 'Listo para enviar'
    notas                   TEXT,

    -- Response data
    fecha_respuesta         DATE,
    dias_sin_respuesta      INT,

    -- Operational metadata
    owner                   TEXT,
    sheet_row_number        INT,                                -- source row number in the Sheet (for traceability and resyncs)
    synced_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(), -- last time Apps Script touched this row
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- CRITICAL: prevents two rows for the same bank+opportunity (anti-duplicate guard)
    CONSTRAINT uq_bank_opportunity UNIQUE (bank_id, opportunity_id)
);

COMMENT ON TABLE  sheet_rows IS 'Mirror of every row across all bank Sheet tabs. Central fact table. Apps Script upserts here.';
COMMENT ON COLUMN sheet_rows.uid IS 'ITEM ID generated by Apps Script. NULL for banks that do not have this column.';
COMMENT ON COLUMN sheet_rows.status_raw IS 'Original unmodified status string from the Sheet. Never overwritten once set, for auditability.';
COMMENT ON COLUMN sheet_rows.status IS 'Normalized status computed from status_raw via normalize_status(). Safe for filtering and grouping.';
COMMENT ON COLUMN sheet_rows.red_flags_raw IS 'Original pipe-separated red flag text from the Sheet. Preserved verbatim.';
COMMENT ON COLUMN sheet_rows.red_flags IS 'Parsed array of individual red flag strings split on | and trimmed.';
COMMENT ON COLUMN sheet_rows.send_trigger IS 'TRUE = row has Enviar/Enviado = Yes. FALSE = explicitly No. NULL = blank/unknown.';
COMMENT ON COLUMN sheet_rows.sheet_row_number IS 'Row number in the Google Sheet (1-indexed). Used by Apps Script to update specific cells.';
COMMENT ON CONSTRAINT uq_bank_opportunity ON sheet_rows IS 'Core anti-duplicate guard. One row per bank per Pipedrive opportunity.';


-- =============================================================================
-- TABLE: dispatch_attempts
-- Records every attempt (successful or not) to dispatch a row to a bank.
-- Append-only. Never update or delete rows here.
-- =============================================================================
CREATE TABLE IF NOT EXISTS dispatch_attempts (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    sheet_row_id    UUID            NOT NULL REFERENCES sheet_rows(id) ON DELETE RESTRICT,
    bank_id         INT             NOT NULL REFERENCES banks(id) ON DELETE RESTRICT,
    opportunity_id  BIGINT          NOT NULL,
    uid             TEXT,                                       -- UID at time of dispatch (snapshot)

    -- Who/what triggered this attempt
    triggered_by    TEXT            NOT NULL,                   -- 'apps_script' | 'manual_relaunch' | 'auto_retry'

    -- Outcome
    status          TEXT            NOT NULL,                   -- 'sent' | 'failed' | 'blocked' | 'duplicate_prevented'
    webhook_url     TEXT,                                       -- destination URL called
    response_body   TEXT,                                       -- raw response from webhook/bank system
    error_message   TEXT,                                       -- error detail on failure

    -- Relaunch guard: if force_flag=true the caller confirmed they want to resend
    force_flag      BOOLEAN         NOT NULL DEFAULT FALSE,

    dispatched_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  dispatch_attempts IS 'Append-only log of every dispatch attempt. Never delete rows.';
COMMENT ON COLUMN dispatch_attempts.force_flag IS 'TRUE means the caller explicitly passed force=true, acknowledging a potential re-send.';
COMMENT ON COLUMN dispatch_attempts.triggered_by IS 'apps_script | manual_relaunch | auto_retry. Used for audit and metrics.';
COMMENT ON COLUMN dispatch_attempts.status IS 'sent | failed | blocked | duplicate_prevented.';


-- =============================================================================
-- TABLE: red_flag_events
-- Each individual red flag extracted from red_flags_raw gets its own row here.
-- This enables frequency analysis and clustering without string-splitting at query time.
-- =============================================================================
CREATE TABLE IF NOT EXISTS red_flag_events (
    id                  UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    sheet_row_id        UUID    NOT NULL REFERENCES sheet_rows(id) ON DELETE CASCADE,
    bank_id             INT     NOT NULL REFERENCES banks(id) ON DELETE RESTRICT,
    opportunity_id      BIGINT  NOT NULL,
    raw_text            TEXT    NOT NULL,                       -- individual red flag text (one per row)
    normalized_reason   TEXT,                                   -- category label filled by clustering process
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  red_flag_events IS 'One row per individual red flag. Enables frequency queries and clustering without runtime string splits.';
COMMENT ON COLUMN red_flag_events.raw_text IS 'Single red flag text, already split from the pipe-separated source string.';
COMMENT ON COLUMN red_flag_events.normalized_reason IS 'Category assigned by clustering (e.g. age_term_exceeded, min_amount, min_income). NULL until clustering runs.';


-- =============================================================================
-- TABLE: event_log
-- Immutable audit trail for every significant action in the system.
-- Append-only. Never update or delete rows here.
-- =============================================================================
CREATE TABLE IF NOT EXISTS event_log (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type      TEXT        NOT NULL,   -- see valid values in comment below
    sheet_row_id    UUID        REFERENCES sheet_rows(id) ON DELETE SET NULL,
    bank_id         INT         REFERENCES banks(id) ON DELETE SET NULL,
    opportunity_id  BIGINT,
    actor           TEXT,                   -- 'apps_script' | 'user:email@domain.com' | 'system'
    payload         JSONB,                  -- arbitrary structured data for the event
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  event_log IS 'Append-only immutable audit trail. Never update or delete rows.';
COMMENT ON COLUMN event_log.event_type IS
    'Valid values: sync | dispatch | relaunch_requested | relaunch_executed | '
    'status_change | red_flag_detected | offer_received | duplicate_prevented | blocked';
COMMENT ON COLUMN event_log.actor IS 'Who triggered the event: apps_script | user:email@domain.com | system.';
COMMENT ON COLUMN event_log.payload IS 'Arbitrary JSON blob with event-specific data (previous status, new status, error, etc.).';


-- =============================================================================
-- INDEXES
-- Chosen to support the dashboard query patterns described in the MVP.
-- =============================================================================

-- sheet_rows: most common filter axes
CREATE INDEX idx_sheet_rows_bank_id           ON sheet_rows (bank_id);
CREATE INDEX idx_sheet_rows_opportunity_id    ON sheet_rows (opportunity_id);
CREATE INDEX idx_sheet_rows_status            ON sheet_rows (status);
CREATE INDEX idx_sheet_rows_uid               ON sheet_rows (uid) WHERE uid IS NOT NULL;
CREATE INDEX idx_sheet_rows_timestamp_sent    ON sheet_rows (timestamp_sent) WHERE timestamp_sent IS NOT NULL;
CREATE INDEX idx_sheet_rows_synced_at         ON sheet_rows (synced_at);

-- sheet_rows: composite for the most common dashboard view (bank + status filter)
CREATE INDEX idx_sheet_rows_bank_status       ON sheet_rows (bank_id, status);

-- sheet_rows: trigram index for client name search
CREATE INDEX idx_sheet_rows_nombre_trgm       ON sheet_rows USING GIN (nombre_cliente gin_trgm_ops);

-- dispatch_attempts
CREATE INDEX idx_dispatch_sheet_row_id        ON dispatch_attempts (sheet_row_id);
CREATE INDEX idx_dispatch_bank_id             ON dispatch_attempts (bank_id);
CREATE INDEX idx_dispatch_opportunity_id      ON dispatch_attempts (opportunity_id);
CREATE INDEX idx_dispatch_dispatched_at       ON dispatch_attempts (dispatched_at);
CREATE INDEX idx_dispatch_status              ON dispatch_attempts (status);

-- red_flag_events
CREATE INDEX idx_red_flag_sheet_row_id        ON red_flag_events (sheet_row_id);
CREATE INDEX idx_red_flag_bank_id             ON red_flag_events (bank_id);
CREATE INDEX idx_red_flag_normalized_reason   ON red_flag_events (normalized_reason) WHERE normalized_reason IS NOT NULL;

-- red_flag_events: trigram index to support similarity clustering
CREATE INDEX idx_red_flag_raw_text_trgm       ON red_flag_events USING GIN (raw_text gin_trgm_ops);

-- event_log
CREATE INDEX idx_event_log_sheet_row_id       ON event_log (sheet_row_id) WHERE sheet_row_id IS NOT NULL;
CREATE INDEX idx_event_log_bank_id            ON event_log (bank_id) WHERE bank_id IS NOT NULL;
CREATE INDEX idx_event_log_event_type         ON event_log (event_type);
CREATE INDEX idx_event_log_created_at         ON event_log (created_at);

-- event_log: composite for timeline queries per row
CREATE INDEX idx_event_log_row_time           ON event_log (sheet_row_id, created_at);


-- =============================================================================
-- FUNCTION: normalize_status(raw text) RETURNS normalized_status
--
-- Maps the messy raw status strings from the Google Sheet to the canonical
-- normalized_status enum. Called by Apps Script during upserts.
--
-- Matching order matters: more specific patterns first.
-- =============================================================================
CREATE OR REPLACE FUNCTION normalize_status(raw TEXT)
RETURNS normalized_status
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
DECLARE
    lower_raw TEXT;
BEGIN
    IF raw IS NULL OR TRIM(raw) = '' THEN
        RETURN 'unknown';
    END IF;

    lower_raw := LOWER(TRIM(raw));

    -- Sent variants: "Enviado ✅", "Enviado", "ENVIADO", "enviado ", "SENT", etc.
    IF lower_raw LIKE 'enviado%'
       OR lower_raw = 'sent'
       OR lower_raw = 'completado'
    THEN
        RETURN 'sent';
    END IF;

    -- Sending / in progress
    IF lower_raw = 'procesando'
       OR lower_raw = 'sending'
    THEN
        RETURN 'sending';
    END IF;

    -- Ready to send
    IF lower_raw LIKE '%listo para enviar%'
       OR lower_raw LIKE '%ready%'
    THEN
        RETURN 'pending_ready';
    END IF;

    -- Blocked by too many banks (validation rule: > 3 banks detected)
    -- Examples: "5 banks detected → blocked (> 3)", "4 banks detected → blocked (> 3)"
    IF lower_raw LIKE '%banks detected%blocked%'
       OR lower_raw LIKE '%blocked%'
    THEN
        RETURN 'blocked_validation';
    END IF;

    -- Failed: draft generated (not actually sent), or hard errors
    IF lower_raw LIKE '%borrador%'
       OR lower_raw LIKE '%no se ha enviado%'
    THEN
        RETURN 'failed';
    END IF;

    -- Failed: system/config errors
    IF lower_raw LIKE '%error%'
       OR lower_raw LIKE '%no existe%'
       OR lower_raw LIKE '%no tenemos correo%'
    THEN
        RETURN 'failed';
    END IF;

    -- Offer received
    IF lower_raw LIKE '%oferta%'
       OR lower_raw LIKE '%offer%received%'
    THEN
        RETURN 'offer_received';
    END IF;

    -- Rejected
    IF lower_raw LIKE '%denegad%'
       OR lower_raw LIKE '%rechazad%'
       OR lower_raw LIKE '%rejected%'
    THEN
        RETURN 'rejected';
    END IF;

    -- More information requested
    IF lower_raw LIKE '%más información%'
       OR lower_raw LIKE '%mas informacion%'
       OR lower_raw LIKE '%more info%'
       OR lower_raw LIKE '%pendiente documentacion%'
    THEN
        RETURN 'more_info_requested';
    END IF;

    -- Relaunch requested
    IF lower_raw LIKE '%relanzar%'
       OR lower_raw LIKE '%relaunch%'
    THEN
        RETURN 'relaunch_requested';
    END IF;

    -- Blocked by red flag (explicit red flag mention)
    IF lower_raw LIKE '%red flag%'
    THEN
        RETURN 'blocked_red_flag';
    END IF;

    -- Blocked by missing documents
    IF lower_raw LIKE '%documentos%'
       OR lower_raw LIKE '%missing%doc%'
    THEN
        RETURN 'blocked_missing_docs';
    END IF;

    -- Ver notas / see notes — treat as unknown until manually reviewed
    IF lower_raw LIKE '%ver nota%'
       OR lower_raw LIKE '%see note%'
    THEN
        RETURN 'unknown';
    END IF;

    RETURN 'unknown';
END;
$$;

COMMENT ON FUNCTION normalize_status(TEXT) IS
    'Maps raw Sheet status strings to the normalized_status enum. '
    'Called during Apps Script upserts. Add new patterns here as new raw values appear in production.';


-- =============================================================================
-- FUNCTION + TRIGGER: update_updated_at
-- Automatically refreshes sheet_rows.updated_at on every UPDATE.
-- =============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sheet_rows_updated_at
    BEFORE UPDATE ON sheet_rows
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TRIGGER trg_sheet_rows_updated_at ON sheet_rows IS
    'Automatically sets updated_at = NOW() on every row update.';


-- =============================================================================
-- ROW LEVEL SECURITY
--
-- SECURITY ARCHITECTURE:
--   - anon  role  : SELECT only (used by Next.js dashboard via supabase-js with anon key)
--   - authenticated role : SELECT only (logged-in users via Supabase Auth)
--   - service_role : bypasses RLS entirely — used by Apps Script server-side calls ONLY
--
-- WARNING: service_role key MUST NEVER be placed in browser/frontend code.
--          It has full unrestricted access to all tables.
--          Store it only in server-side environment variables (Apps Script, edge functions).
-- =============================================================================

-- Enable RLS on every table
ALTER TABLE banks             ENABLE ROW LEVEL SECURITY;
ALTER TABLE sheet_rows        ENABLE ROW LEVEL SECURITY;
ALTER TABLE dispatch_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE red_flag_events   ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_log         ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- banks: read-only for anon and authenticated
-- ---------------------------------------------------------------------------
CREATE POLICY "banks_select_anon"
    ON banks
    FOR SELECT
    TO anon
    USING (TRUE);

CREATE POLICY "banks_select_authenticated"
    ON banks
    FOR SELECT
    TO authenticated
    USING (TRUE);

-- No INSERT/UPDATE/DELETE policies for anon or authenticated.
-- service_role bypasses RLS and handles all writes.


-- ---------------------------------------------------------------------------
-- sheet_rows: read-only for anon and authenticated
-- ---------------------------------------------------------------------------
CREATE POLICY "sheet_rows_select_anon"
    ON sheet_rows
    FOR SELECT
    TO anon
    USING (TRUE);

CREATE POLICY "sheet_rows_select_authenticated"
    ON sheet_rows
    FOR SELECT
    TO authenticated
    USING (TRUE);


-- ---------------------------------------------------------------------------
-- dispatch_attempts: read-only for anon and authenticated
-- ---------------------------------------------------------------------------
CREATE POLICY "dispatch_attempts_select_anon"
    ON dispatch_attempts
    FOR SELECT
    TO anon
    USING (TRUE);

CREATE POLICY "dispatch_attempts_select_authenticated"
    ON dispatch_attempts
    FOR SELECT
    TO authenticated
    USING (TRUE);


-- ---------------------------------------------------------------------------
-- red_flag_events: read-only for anon and authenticated
-- ---------------------------------------------------------------------------
CREATE POLICY "red_flag_events_select_anon"
    ON red_flag_events
    FOR SELECT
    TO anon
    USING (TRUE);

CREATE POLICY "red_flag_events_select_authenticated"
    ON red_flag_events
    FOR SELECT
    TO authenticated
    USING (TRUE);


-- ---------------------------------------------------------------------------
-- event_log: read-only for anon and authenticated
-- ---------------------------------------------------------------------------
CREATE POLICY "event_log_select_anon"
    ON event_log
    FOR SELECT
    TO anon
    USING (TRUE);

CREATE POLICY "event_log_select_authenticated"
    ON event_log
    FOR SELECT
    TO authenticated
    USING (TRUE);


-- =============================================================================
-- End of migration 001_init.sql
-- =============================================================================
