-- =============================================================================
-- Migration: 003_red_flag_sheet_row_nullable.sql
--
-- Makes sheet_row_id nullable in red_flag_events.
-- During sync from Apps Script we don't have the UUID of the sheet_row at
-- insert time (it's generated by the DB). We allow NULL here and backfill
-- sheet_row_id later with a JOIN on (bank_id, opportunity_id).
-- =============================================================================

ALTER TABLE red_flag_events
    ALTER COLUMN sheet_row_id DROP NOT NULL;
