/** Active banks — mirrors packages/shared/types.ts ACTIVE_BANKS */
export const ACTIVE_BANKS = [
  { slug: 'santander',     name: 'Santander'     },
  { slug: 'uci',           name: 'UCI'           },
  { slug: 'ing',           name: 'ING'           },
  { slug: 'ruralnostra',   name: 'Ruralnostra'   },
  { slug: 'ibercaja',      name: 'Ibercaja'      },
  { slug: 'cr_teruel',     name: 'CR Teruel'     },
  { slug: 'unicaja',       name: 'Unicaja'       },
  { slug: 'no_bank_fee',   name: 'No Bank Fee'   },
  { slug: 'cr_asturias',   name: 'CR Asturias'   },
  { slug: 'cr_aragon',     name: 'CR Aragón'     },
  { slug: 'cr_granada',    name: 'CR Granada'    },
  { slug: 'laboral_kutxa', name: 'Laboral Kutxa' },
  { slug: 'deutsche_bank', name: 'Deutsche Bank' },
  { slug: 'eurocajarural', name: 'EuroCajaRural' },
  { slug: 'myinvestor',    name: 'MyInvestor'    },
  { slug: 'cr_del_sur',    name: 'CR del Sur'    },
  { slug: 'globalcaja',    name: 'Globalcaja'    },
  { slug: 'caixa_popular', name: 'Caixa Popular' },
  { slug: 'cajamar',       name: 'Cajamar'       },
  { slug: 'bankinter',     name: 'Bankinter'     },
  { slug: 'kutxabank',      name: 'Kutxabank'              },
  { slug: 'abanca',         name: 'Abanca'                 },
  { slug: 'cr_extremadura', name: 'CR Extremadura'         },
  { slug: 'sabadell',       name: 'Sabadell no residentes' },
  { slug: 'banca_360',      name: 'Banca 360 / MSF 360'   },
] as const
